# ETL dos dados

In [37]:
import pandas as pd

df = pd.read_excel("dados.xlsx", sheet_name="Planejamento")

In [33]:
df.columns = df.columns.str.strip()
df.loc[:, ['Import Test Case Name','Test Case Target', 'Card de Desenvolvimento', 'Sistema','Link do Card de Desenvolvimento','Action']].head(25)

,Import Test Case Name,Test Case Target,Card de Desenvolvimento,Sistema,Link do Card de Desenvolvimento,Action
0,Card STS0149727 - TC 199_Modal norma_Upload e ...,NaN,Card STS0149727 - TC 199,NORTEC,[Nortec] Projeto Norma – Upload e Acesso a Doc...,Pré-condição: ser perfil Nortec
1,NaN,NaN,NaN,NaN,NaN,Acessar o NORTEC pelo link: Acessar o NORTEC ...
2,NaN,NaN,NaN,NaN,NaN,Clicar em Subcomissão
3,NaN,NaN,NaN,NaN,NaN,Pesquisar pela subcomissão 44
4,NaN,NaN,NaN,NaN,NaN,Clicar no detalhe da subcomissão
5,NaN,NaN,NaN,NaN,NaN,Clicar em Plano de trabalho (Reuniões GT)
6,NaN,NaN,NaN,NaN,NaN,Selecionar um projeto de elaboração
7,NaN,NaN,NaN,NaN,NaN,Ir para o submenu de modal norma\n
8,NaN,NaN,NaN,NaN,NaN,Clicar no botão para abrir/editar no sharepoint
9,NaN,NaN,NaN,NaN,NaN,Clicar no botão para anexar um documento tipo PDF
10,NaN,NaN,NaN,NaN,NaN,Selecionar um documento
11,NaN,NaN,NaN,NaN,NaN,Realizar upload
12,NaN,NaN,NaN,NaN,NaN,NaN
13,Card STS0149727 - TC 200_Modal norma_Acesso ao...,NaN,Card STS0149727 - TC 200,NORTEC,[Nortec] Projeto Norma – Upload e Acesso a Doc...,Pré-condição: NÃO ser perfil Nortec
14,NaN,NaN,NaN,NaN,NaN,Acessar o NORTEC pelo link: Acessar o NORTEC ...
15,NaN,NaN,NaN,NaN,NaN,Clicar em Subcomissão
16,NaN,NaN,NaN,NaN,NaN,Pesquisar pela subcomissão 44
17,NaN,NaN,NaN,NaN,NaN,Clicar no detalhe da subcomissão
18,NaN,NaN,NaN,NaN,NaN,Clicar em Plano de trabalho (Reuniões GT)
19,NaN,NaN,NaN,NaN,NaN,Selecionar um projeto de elaboração
20,NaN,NaN,NaN,NaN,NaN,Clicar no modal norma
21,NaN,NaN,NaN,NaN,NaN,Clicar no botão para abrir/editar no sharepoint
22,NaN,NaN,NaN,NaN,NaN,NaN
23,Card STS0149727 - TC 201_Modal norma_Upload do...,NaN,Card STS0149727 - TC 201,NORTEC,[Nortec] Projeto Norma – Upload e Acesso a Doc...,Pré-condição: ser perfil Nortec
24,NaN,NaN,NaN,NaN,NaN,Acessar o NORTEC pelo link: Acessar o NORTEC ...

In [42]:
# Lista das colunas que quero
colunas_desejadas = ['Import Test Case Name','Test Case Target', 'Card de Desenvolvimento', 'Sistema','Link do Card de Desenvolvimento']

# Novo DataFrame só com essas colunas
df_tabela = df[colunas_desejadas].copy()

df_tabela = df_tabela.dropna(how='all')

df_tabela.head(50)

,Import Test Case Name,Test Case Target,Card de Desenvolvimento,Sistema,Link do Card de Desenvolvimento
0,Card STS0149727 - TC 199_Modal norma_Upload e ...,NaN,Card STS0149727 - TC 199,NORTEC,[Nortec] Projeto Norma – Upload e Acesso a Doc...
13,Card STS0149727 - TC 200_Modal norma_Acesso ao...,NaN,Card STS0149727 - TC 200,NORTEC,[Nortec] Projeto Norma – Upload e Acesso a Doc...
23,Card STS0149727 - TC 201_Modal norma_Upload do...,NaN,Card STS0149727 - TC 201,NORTEC,[Nortec] Projeto Norma – Upload e Acesso a Doc...
40,Card STS0149727 - TC 202_Modal norma_Upload do...,NaN,Card STS0149727 - TC 202,NORTEC,[Nortec] Projeto Norma – Upload e Acesso a Doc...
53,"Card STS0149727 - TC 203_Modal ""Documentos de ...",NaN,Card STS0149727 - TC 203,NORTEC,[Nortec] Projeto Norma – Upload e Acesso a Doc...
66,Card STS0149727 - TC 204_Modal norma_Upload do...,NaN,Card STS0149727 - TC 204,NORTEC,[Nortec] Projeto Norma – Upload e Acesso a Doc...
79,Card STS0149727 - TC 205_Modal norma_Upload do...,NaN,Card STS0149727 - TC 205,NORTEC,[Nortec] Projeto Norma – Upload e Acesso a Doc...
92,Card STS0149717 - TC 206_Modal norma_Assistir ...,NaN,Card STS0149717 - TC 206,NORTEC,[Nortec] Página Inicial – Vídeo de orientação ...
95,Card STS0149717 - TC 207_Modal norma_Não ter a...,NaN,Card STS0149717 - TC 207,NORTEC,[Nortec] Página Inicial – Vídeo de orientação ...
98,Card STS0149717 - TC 208_Modal norma_Não ter a...,NaN,Card STS0149717 - TC 208,NORTEC,[Nortec] Página Inicial – Vídeo de orientação ...
101,Card STS0149717 - TC 209_Modal norma_Não ter a...,NaN,Card STS0149717 - TC 209,NORTEC,[Nortec] Página Inicial – Vídeo de orientação ...
104,Card STS0149722 - TC 210_Modal norma_Edição do...,NaN,Card STS0149722 - TC 210,NORTEC,[Nortec] Código de Origem – Editar Tipo (Órgão...
112,Card STS0149722 - TC 211_Modal norma_Edição do...,NaN,Card STS0149722 - TC 211,NORTEC,[Nortec] Código de Origem – Editar Tipo (Órgão...
120,Card STS0149722 - TC 212_Modal norma_Edição do...,NaN,Card STS0149722 - TC 212,NORTEC,[Nortec] Código de Origem – Editar Tipo (Órgão...
128,Card STS0149722 - TC 213_Modal norma_Edição do...,NaN,Card STS0149722 - TC 213,NORTEC,[Nortec] Código de Origem – Editar Tipo (Órgão...
136,Card STS0149722 - TC 214_Modal norma_Edição do...,NaN,Card STS0149722 - TC 214,NORTEC,[Nortec] Código de Origem – Editar Tipo (Órgão...
144,Card STS0149722 - TC 215_Modal norma_Edição do...,NaN,Card STS0149722 - TC 215,NORTEC,[Nortec] Código de Origem – Editar Tipo (Órgão...
152,Card STS0149722 - TC 216_Modal norma_Edição do...,NaN,Card STS0149722 - TC 216,NORTEC,[Nortec] Código de Origem – Editar Tipo (Órgão...
157,Card STS0149722 - TC 217_Modal norma_Edição do...,NaN,Card STS0149722 - TC 217,NORTEC,[Nortec] Código de Origem – Editar Tipo (Órgão...
167,Card STS0149722 - TC 218_Código de origem_Noti...,NaN,Card STS0149722 - TC 218,NORTEC,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
177,Card STS0149722 - TC 219_Código de origem_Noti...,NaN,Card STS0149722 - TC 219,NORTEC,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
187,Card STS0149722 - TC 220_Código de origem_Noti...,NaN,Card STS0149722 - TC 220,NORTEC,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
197,Card STS0149722 - TC 221_Código de origem_Noti...,NaN,Card STS0149722 - TC 221,NORTEC,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
206,Card STS0149722 - TC 222_Código de origem_Noti...,NaN,Card STS0149722 - TC 222,NORTEC,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
213,Card STS0149722 - TC 223_Código de origem_Noti...,NaN,Card STS0149722 - TC 223,NORTEC,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
225,Card STS0149722 - TC 224_Código de origem_Noti...,NaN,Card STS0149722 - TC 224,NORTEC,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
238,Card STS0149722 - TC 225_Código de origem_Noti...,NaN,Card STS0149722 - TC 225,NORTEC,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
251,Card STS0149722 - TC 226_Código de origem_Noti...,NaN,Card STS0149722 - TC 226,NORTEC,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
266,Card STS0148664 - TC 227_Código de origem_Gest...,NaN,Card STS0148664 - TC 227,NORTEC,https://petrobras.service-now.com/sn_safe_stor...
279,Card STS0148664 - TC 228_Código de origem_Gest...,NaN,Card STS0148664 - TC 228,NORTEC,https://petrobras.service-now.com/sn_safe_stor...
292,Card STS0148664 - TC 229_Código de origem_Gest...,NaN,Card STS0148664 - TC 229,NORTEC,https://petrobras.service-now.com/sn_safe_stor...
305,Card STS0148664 - TC 230_Código de origem_Gest...,NaN,Card STS0148664 - TC 230,NORTEC,https://petrobras.service-now.com/sn_safe_stor...
314,Card STS0148664 - TC 231_Código de origem_Gest...,NaN,Card STS0148664 - TC 231,NORTEC,https://petrobras.service-now.com/sn_safe_stor...
323,Card STS0148664 - TC 232_Código de origem_Gest...,NaN,Card STS0148664 - TC 232,NORTEC,https://petrobras.service-now.com/sn_safe_stor...
332,Card STS0148664 - TC 233_Código de origem_Gest...,NaN,Card STS0148664 - TC 233,NORTEC,https://petrobras.service-now.com/sn_safe_stor...
345,Card STS0148664 - TC 234_Código de origem_Gest...,NaN,Card STS0148664 - TC 234,NORTEC,https://petrobras.service-now.com/sn_safe_stor...
360,Card STS0148664 - TC 235_Código de origem_Gest...,NaN,Card STS0148664 - TC 235,NORTEC,https://petrobras.service-now.com/sn_safe_stor...
377,Card STS0148664 - TC 236_Subcomissão_Criação d...,NaN,Card STS0148664 - TC 236,NORTEC,https://petrobras.service-now.com/sn_safe_stor...
388,Card STS0148664 - TC 237_Subcomissão_Criação d...,NaN,Card STS0148664 - TC 237,NORTEC,https://petrobras.service-now.com/sn_safe_stor...