# Rascunho dos processos de dados

In [ ]:
import pandas as pd

df = pd.read_excel("dados.xlsx", sheet_name="Planejamento")

In [ ]:
df.columns = df.columns.str.strip()
df.loc[:, ['ID','Import Test Case Name','Test Case Target', 'Card de Desenvolvimento', 'Sistema','Responsável','Link do Card de Desenvolvimento']].head(25)

,ID,Import Test Case Name,Test Case Target,Card de Desenvolvimento,Sistema,Responsável,Link do Card de Desenvolvimento
0,199.0,Card STS0149727 - TC 199_Modal norma_Upload e ...,NaN,Card STS0149727 - TC 199,NORTEC,G7E4,[Nortec] Projeto Norma – Upload e Acesso a Doc...
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,200.0,Card STS0149727 - TC 200_Modal norma_Acesso ao...,NaN,Card STS0149727 - TC 200,NORTEC,G7E4,[Nortec] Projeto Norma – Upload e Acesso a Doc...
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,201.0,Card STS0149727 - TC 201_Modal norma_Upload do...,NaN,Card STS0149727 - TC 201,NORTEC,G7E4,[Nortec] Projeto Norma – Upload e Acesso a Doc...
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Lista das colunas que quero
colunas_desejadas = ['ID','Import Test Case Name','Test Case Target', 'Card de Desenvolvimento', 'Sistema','Responsável','Link do Card de Desenvolvimento']

# Novo DataFrame só com essas colunas
df_tabela = df[colunas_desejadas].copy()

df_tabela = df_tabela.dropna(how='all') # Remove linhas onde todas as células são NaN
df_tabela["ID"] = df_tabela["ID"].astype("Int64")
df_tabela = df_tabela.apply(lambda col: col.apply(lambda x: x.strip() if isinstance(x, str) else x)) # Remove espaços em branco das células

df_tabela.head(50)

,ID,Import Test Case Name,Test Case Target,Card de Desenvolvimento,Sistema,Responsável,Link do Card de Desenvolvimento
0,199,Card STS0149727 - TC 199_Modal norma_Upload e ...,NaN,Card STS0149727 - TC 199,NORTEC,G7E4,[Nortec] Projeto Norma – Upload e Acesso a Doc...
13,200,Card STS0149727 - TC 200_Modal norma_Acesso ao...,NaN,Card STS0149727 - TC 200,NORTEC,G7E4,[Nortec] Projeto Norma – Upload e Acesso a Doc...
23,201,Card STS0149727 - TC 201_Modal norma_Upload do...,NaN,Card STS0149727 - TC 201,NORTEC,G7E4,[Nortec] Projeto Norma – Upload e Acesso a Doc...
40,202,Card STS0149727 - TC 202_Modal norma_Upload do...,NaN,Card STS0149727 - TC 202,NORTEC,G7E4,[Nortec] Projeto Norma – Upload e Acesso a Doc...
53,203,"Card STS0149727 - TC 203_Modal ""Documentos de ...",NaN,Card STS0149727 - TC 203,NORTEC,G7E4,[Nortec] Projeto Norma – Upload e Acesso a Doc...
66,204,Card STS0149727 - TC 204_Modal norma_Upload do...,NaN,Card STS0149727 - TC 204,NORTEC,G7E4,[Nortec] Projeto Norma – Upload e Acesso a Doc...
79,205,Card STS0149727 - TC 205_Modal norma_Upload do...,NaN,Card STS0149727 - TC 205,NORTEC,G7E4,[Nortec] Projeto Norma – Upload e Acesso a Doc...
92,206,Card STS0149717 - TC 206_Modal norma_Assistir ...,NaN,Card STS0149717 - TC 206,NORTEC,G7E4,[Nortec] Página Inicial – Vídeo de orientação ...
95,207,Card STS0149717 - TC 207_Modal norma_Não ter a...,NaN,Card STS0149717 - TC 207,NORTEC,G7E4,[Nortec] Página Inicial – Vídeo de orientação ...
98,208,Card STS0149717 - TC 208_Modal norma_Não ter a...,NaN,Card STS0149717 - TC 208,NORTEC,G7E4,[Nortec] Página Inicial – Vídeo de orientação ...
101,209,Card STS0149717 - TC 209_Modal norma_Não ter a...,NaN,Card STS0149717 - TC 209,NORTEC,G7E4,[Nortec] Página Inicial – Vídeo de orientação ...
104,210,Card STS0149722 - TC 210_Modal norma_Edição do...,NaN,Card STS0149722 - TC 210,NORTEC,G7E4,[Nortec] Código de Origem – Editar Tipo (Órgão...
112,211,Card STS0149722 - TC 211_Modal norma_Edição do...,NaN,Card STS0149722 - TC 211,NORTEC,G7E4,[Nortec] Código de Origem – Editar Tipo (Órgão...
120,212,Card STS0149722 - TC 212_Modal norma_Edição do...,NaN,Card STS0149722 - TC 212,NORTEC,G7E4,[Nortec] Código de Origem – Editar Tipo (Órgão...
128,213,Card STS0149722 - TC 213_Modal norma_Edição do...,NaN,Card STS0149722 - TC 213,NORTEC,G7E4,[Nortec] Código de Origem – Editar Tipo (Órgão...
136,214,Card STS0149722 - TC 214_Modal norma_Edição do...,NaN,Card STS0149722 - TC 214,NORTEC,G7E4,[Nortec] Código de Origem – Editar Tipo (Órgão...
144,215,Card STS0149722 - TC 215_Modal norma_Edição do...,NaN,Card STS0149722 - TC 215,NORTEC,G7E4,[Nortec] Código de Origem – Editar Tipo (Órgão...
152,216,Card STS0149722 - TC 216_Modal norma_Edição do...,NaN,Card STS0149722 - TC 216,NORTEC,G7E4,[Nortec] Código de Origem – Editar Tipo (Órgão...
157,217,Card STS0149722 - TC 217_Modal norma_Edição do...,NaN,Card STS0149722 - TC 217,NORTEC,G7E4,[Nortec] Código de Origem – Editar Tipo (Órgão...
167,218,Card STS0149722 - TC 218_Código de origem_Noti...,NaN,Card STS0149722 - TC 218,NORTEC,G7E4,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
177,219,Card STS0149722 - TC 219_Código de origem_Noti...,NaN,Card STS0149722 - TC 219,NORTEC,G7E4,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
187,220,Card STS0149722 - TC 220_Código de origem_Noti...,NaN,Card STS0149722 - TC 220,NORTEC,G7E4,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
197,221,Card STS0149722 - TC 221_Código de origem_Noti...,NaN,Card STS0149722 - TC 221,NORTEC,G7E4,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
206,222,Card STS0149722 - TC 222_Código de origem_Noti...,NaN,Card STS0149722 - TC 222,NORTEC,G7E4,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
213,223,Card STS0149722 - TC 223_Código de origem_Noti...,NaN,Card STS0149722 - TC 223,NORTEC,G7E4,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
225,224,Card STS0149722 - TC 224_Código de origem_Noti...,NaN,Card STS0149722 - TC 224,NORTEC,G7E4,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
238,225,Card STS0149722 - TC 225_Código de origem_Noti...,NaN,Card STS0149722 - TC 225,NORTEC,G7E4,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
251,226,Card STS0149722 - TC 226_Código de origem_Noti...,NaN,Card STS0149722 - TC 226,NORTEC,G7E4,VTB: NORTEC (COS-A): Current Sprint | ServiceNow
266,227,Card STS0148664 - TC 227_Código de origem_Gest...,NaN,Card STS0148664 - TC 227,NORTEC,G7E4,https://petrobras.service-now.com/sn_safe_stor...
279,228,Card STS0148664 - TC 228_Código de origem_Gest...,NaN,Card STS0148664 - TC 228,NORTEC,G7E4,https://petrobras.service-now.com/sn_safe_stor...
292,229,Card STS0148664 - TC 229_Código de origem_Gest...,NaN,Card STS0148664 - TC 229,NORTEC,G7E4,https://petrobras.service-now.com/sn_safe_stor...
305,230,Card STS0148664 - TC 230_Código de origem_Gest...,NaN,Card STS0148664 - TC 230,NORTEC,G7E4,https://petrobras.service-now.com/sn_safe_stor...
314,231,Card STS0148664 - TC 231_Código de origem_Gest...,NaN,Card STS0148664 - TC 231,NORTEC,G7E4,https://petrobras.service-now.com/sn_safe_stor...
323,232,Card STS0148664 - TC 232_Código de origem_Gest...,NaN,Card STS0148664 - TC 232,NORTEC,G7E4,https://petrobras.service-now.com/sn_safe_stor...
332,233,Card STS0148664 - TC 233_Código de origem_Gest...,NaN,Card STS0148664 - TC 233,NORTEC,G7E4,https://petrobras.service-now.com/sn_safe_stor...
345,234,Card STS0148664 - TC 234_Código de origem_Gest...,NaN,Card STS0148664 - TC 234,NORTEC,G7E4,https://petrobras.service-now.com/sn_safe_stor...
360,235,Card STS0148664 - TC 235_Código de origem_Gest...,NaN,Card STS0148664 - TC 235,NORTEC,G7E4,https://petrobras.service-now.com/sn_safe_stor...
377,236,Card STS0148664 - TC 236_Subcomissão_Criação d...,NaN,Card STS0148664 - TC 236,NORTEC,G7E4,https://petrobras.service-now.com/sn_safe_stor...
388,237,Card STS0148664 - TC 237_Subcomissão_Criação d...,NaN,Card STS0148664 - TC 237,NORTEC,G7E4,https://petrobras.service-now.com/sn_safe_stor...

In [ ]:
coluna_titulo = ["ID"]

# Novo DataFrame só com essas colunas
df_titulo = df[coluna_titulo].copy()

df_titulo = df_titulo.dropna(how='all') # Remove linhas onde todas as células são NaN
df_titulo["ID"] = df_titulo["ID"].astype("Int64")
df_titulo = df_titulo.apply(lambda col: col.apply(lambda x: x.strip() if isinstance(x, str) else x)) # Remove espaços em branco das células

df_titulo.head(50)